ALTER SYSTEM SET MAX_CONNECTIONS=10;
ALTER SYSTEM SET SHARED_BUFFERS='1GB';
ALTER SYSTEM SET TEMP_BUFFERS='8MB';
ALTER SYSTEM SET WORK_MEM='64MB';
ALTER SYSTEM SET CHECKPOINT_TIMEOUT='15min';
ALTER SYSTEM SET EFFECTIVE_CACHE_SIZE='3GB';
ALTER SYSTEM SET FSYNC=ON;
ALTER SYSTEM SET COMMIT_DELAY=0;

ALTER SYSTEM SET LOGGING_COLLECTOR=on;
ALTER SYSTEM SET LOG_DESTINATION='csvlog';
ALTER SYSTEM SET LOG_DIRECTORY='log';
ALTER SYSTEM SET LOG_FILENAME='postgresql-%Y-%m-%d_%H%M%S.csv';
ALTER SYSTEM SET LOG_MIN_MESSAGES=error;
ALTER SYSTEM SET LOG_DISCONNECTIONS=on;
ALTER SYSTEM SET LOG_DURATION=on;

ALTER SYSTEM SET LISTEN_ADDRESSES='*';
ALTER SYSTEM SET UNIX_SOCKET_DIRECTORIES='/tmp';